Repository precice/systemtests, pull requests merged in 2020-01, with the labels that each got.

#150 Fix of-of and of-of_np
  tests/TestCompose_of-of/docker-compose.yml
  tests/TestCompose_of-of_np/docker-compose.yml
Labels: bug, help wanted

#148 Fix tests failing due to no output
  .travis.yml
  compare_results.sh
  silent_compose.sh
  system_testing.py
  tests/TestCompose_dealii-of/Dockerfile.tutorial_data
  tests/TestCompose_dealii-of/docker-compose.yml
  tests/TestCompose_fe-fe.Ubuntu1804.home/Dockerfile.tutorial_data
  tests/TestCompose_nutils-of.Ubuntu1804/Dockerfile.tutorial_data
  tests/TestCompose_nutils-of.Ubuntu1804/docker-compose.yml
  tests/TestCompose_of-ccx/Dockerfile.tutorial_data
  tests/TestCompose_of-ccx/precice-config.xml
  tests/TestCompose_of-ccx/precice-config_serial.xml
  tests/TestCompose_of-ccx_fsi.Ubuntu1604.home.PETSc/Dockerfile.tutorial_data
  tests/TestCompose_of-of/docker-compose.yml
  tests/TestCompose_of-of_np/docker-compose.yml
  tests/TestCompose_su2-ccx/Dockerfile.tutorial_data
  tests/TestCompose_su2-ccx/docker-compose.yml
Labels: bug

#129 Add tests for bindings on Ubuntu 18.04
  .travis.yml
Labels: enhancement

#163 Install Eigen from source for Ubuntu 16.04
  precice/Dockerfile.Ubuntu1604.home
  precice/Dockerfile.Ubuntu1604.package
  precice/Dockerfile.Ubuntu1604.sudo
Labels: bug

#166 Add installation of pkg-config
  precice/Dockerfile.Ubuntu1604.home
  precice/Dockerfile.Ubuntu1604.package
  precice/Dockerfile.Ubuntu1604.sudo
Labels: bug
